//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.11 at 01:44:21 ÏÂÎç CST 
//


package com.tongtech.sprint;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}worklogdetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tasktype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taskkey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tasksummary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taskstatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tasktimespent" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="tasklogtimespent" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="tasklogworkcount" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "worklogdetail"
})
@XmlRootElement(name = "taskdetail")
public class Taskdetail {

    protected List<Worklogdetail> worklogdetail;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String tasktype;
    @XmlAttribute
    protected String taskkey;
    @XmlAttribute
    protected String tasksummary;
    @XmlAttribute
    protected String taskstatus;
    @XmlAttribute
    protected Double tasktimespent;
    @XmlAttribute
    protected Double tasklogtimespent;
    @XmlAttribute
    protected Integer tasklogworkcount;

    /**
     * Gets the value of the worklogdetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the worklogdetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorklogdetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Worklogdetail }
     * 
     * 
     */
    public List<Worklogdetail> getWorklogdetail() {
        if (worklogdetail == null) {
            worklogdetail = new ArrayList<Worklogdetail>();
        }
        return this.worklogdetail;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the tasktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasktype() {
        return tasktype;
    }

    /**
     * Sets the value of the tasktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasktype(String value) {
        this.tasktype = value;
    }

    /**
     * Gets the value of the taskkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskkey() {
        return taskkey;
    }

    /**
     * Sets the value of the taskkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskkey(String value) {
        this.taskkey = value;
    }

    /**
     * Gets the value of the tasksummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTasksummary() {
        return tasksummary;
    }

    /**
     * Sets the value of the tasksummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTasksummary(String value) {
        this.tasksummary = value;
    }

    /**
     * Gets the value of the taskstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskstatus() {
        return taskstatus;
    }

    /**
     * Sets the value of the taskstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskstatus(String value) {
        this.taskstatus = value;
    }

    /**
     * Gets the value of the tasktimespent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTasktimespent() {
        return tasktimespent;
    }

    /**
     * Sets the value of the tasktimespent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTasktimespent(Double value) {
        this.tasktimespent = value;
    }

    /**
     * Gets the value of the tasklogtimespent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTasklogtimespent() {
        return tasklogtimespent;
    }

    /**
     * Sets the value of the tasklogtimespent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTasklogtimespent(Double value) {
        this.tasklogtimespent = value;
    }

    /**
     * Gets the value of the tasklogworkcount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTasklogworkcount() {
        return tasklogworkcount;
    }

    /**
     * Sets the value of the tasklogworkcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTasklogworkcount(Integer value) {
        this.tasklogworkcount = value;
    }

}
