//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 06:19:08 ÏÂÎç CST 
//


package com.tongtech.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}worklogdetail" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="issuetype" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="issuekey" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="issuesummary" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "worklogdetail"
})
@XmlRootElement(name = "logdetail")
public class Logdetail {

    protected List<Worklogdetail> worklogdetail;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String issuetype;
    @XmlAttribute
    protected String issuekey;
    @XmlAttribute
    protected String issuesummary;

    /**
     * Gets the value of the worklogdetail property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the worklogdetail property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorklogdetail().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Worklogdetail }
     * 
     * 
     */
    public List<Worklogdetail> getWorklogdetail() {
        if (worklogdetail == null) {
            worklogdetail = new ArrayList<Worklogdetail>();
        }
        return this.worklogdetail;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the issuetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuetype() {
        return issuetype;
    }

    /**
     * Sets the value of the issuetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuetype(String value) {
        this.issuetype = value;
    }

    /**
     * Gets the value of the issuekey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuekey() {
        return issuekey;
    }

    /**
     * Sets the value of the issuekey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuekey(String value) {
        this.issuekey = value;
    }

    /**
     * Gets the value of the issuesummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssuesummary() {
        return issuesummary;
    }

    /**
     * Sets the value of the issuesummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssuesummary(String value) {
        this.issuesummary = value;
    }

}
