//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.04 at 06:19:08 ÏÂÎç CST 
//


package com.tongtech.project;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}project" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}duetaskbyprojects" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}storystats" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}peoplestats" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}totalpeoplestats" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}valuationstats" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}logdetails" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startdate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="enddate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "project",
    "duetaskbyprojects",
    "storystats",
    "peoplestats",
    "totalpeoplestats",
    "valuationstats",
    "logdetails"
})
@XmlRootElement(name = "projects")
public class Projects {

    protected List<Project> project;
    protected List<Duetaskbyprojects> duetaskbyprojects;
    protected List<Storystats> storystats;
    protected List<Peoplestats> peoplestats;
    protected List<Totalpeoplestats> totalpeoplestats;
    protected List<Valuationstats> valuationstats;
    protected List<Logdetails> logdetails;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String startdate;
    @XmlAttribute
    protected String enddate;

    /**
     * Gets the value of the project property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the project property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Project }
     * 
     * 
     */
    public List<Project> getProject() {
        if (project == null) {
            project = new ArrayList<Project>();
        }
        return this.project;
    }

    /**
     * Gets the value of the duetaskbyprojects property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the duetaskbyprojects property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDuetaskbyprojects().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Duetaskbyprojects }
     * 
     * 
     */
    public List<Duetaskbyprojects> getDuetaskbyprojects() {
        if (duetaskbyprojects == null) {
            duetaskbyprojects = new ArrayList<Duetaskbyprojects>();
        }
        return this.duetaskbyprojects;
    }

    /**
     * Gets the value of the storystats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the storystats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStorystats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Storystats }
     * 
     * 
     */
    public List<Storystats> getStorystats() {
        if (storystats == null) {
            storystats = new ArrayList<Storystats>();
        }
        return this.storystats;
    }

    /**
     * Gets the value of the peoplestats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the peoplestats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeoplestats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Peoplestats }
     * 
     * 
     */
    public List<Peoplestats> getPeoplestats() {
        if (peoplestats == null) {
            peoplestats = new ArrayList<Peoplestats>();
        }
        return this.peoplestats;
    }

    /**
     * Gets the value of the totalpeoplestats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the totalpeoplestats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotalpeoplestats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Totalpeoplestats }
     * 
     * 
     */
    public List<Totalpeoplestats> getTotalpeoplestats() {
        if (totalpeoplestats == null) {
            totalpeoplestats = new ArrayList<Totalpeoplestats>();
        }
        return this.totalpeoplestats;
    }

    /**
     * Gets the value of the valuationstats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valuationstats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValuationstats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Valuationstats }
     * 
     * 
     */
    public List<Valuationstats> getValuationstats() {
        if (valuationstats == null) {
            valuationstats = new ArrayList<Valuationstats>();
        }
        return this.valuationstats;
    }

    /**
     * Gets the value of the logdetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the logdetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLogdetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Logdetails }
     * 
     * 
     */
    public List<Logdetails> getLogdetails() {
        if (logdetails == null) {
            logdetails = new ArrayList<Logdetails>();
        }
        return this.logdetails;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartdate() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartdate(String value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the enddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnddate() {
        return enddate;
    }

    /**
     * Sets the value of the enddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnddate(String value) {
        this.enddate = value;
    }

}
